### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptography'

### ISSUE THREAD

**Issue by raiubreaksthings** [c-herz/TMOHS1-Root-Utility#10]
I am trying to run this from terminal on a macbook pro non m1. 

I am getting this error when running the "python ./rootScript.py" 

username@usernam-Pro TMOHS1-Root-Utility-main % python ./rootScript.py
Traceback (most recent call last):
  File "/Users/usernam/Desktop/TMOHS1-Root-Utility-main/./rootScript.py", line 15, in <module>
    from cryptography.hazmat.primitives.ciphers import algorithms, modes, Cipher
ModuleNotFoundError: No module named 'cryptography'
username@username-MacBook-Pro TMOHS1-Root-Utility-main % 

I have run pip install -r requirements.txt and do not get any errors. I see the following:
Requirement already satisfied: cryptography==38.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (38.0.1)
Requirement already satisfied: requests==2.26.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (2.26.0)
Requirement already satisfied: pandas==1.5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (1.5.1)
Requirement already satisfied: paramiko==2.11.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.11.0)
Requirement already satisfied: pip==22.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (22.3)
Requirement already satisfied: molecule==4.0.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (4.0.3)
Requirement already satisfied: sh==1.14.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (1.14.3)
Requirement already satisfied: pycryptodome==3.15.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (3.15.0)
Requirement already satisfied: cffi>=1.12 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cryptography==38.0.1->-r requirements.txt (line 1)) (1.15.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (1.26.12)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (2022.9.24)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.26.0->-r requirements.txt (line 2)) (3.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas==1.5.1->-r requirements.txt (line 3)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas==1.5.1->-r requirements.txt (line 3)) (2022.5)
Requirement already satisfied: numpy>=1.21.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from pandas==1.5.1->-r requirements.txt (line 3)) (1.23.4)
Requirement already satisfied: bcrypt>=3.1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from paramiko==2.11.0->-r requirements.txt (line 4)) (4.0.1)
Requirement already satisfied: pynacl>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from paramiko==2.11.0->-r requirements.txt (line 4)) (1.5.0)
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from paramiko==2.11.0->-r requirements.txt (line 4)) (1.16.0)
Requirement already satisfied: ansible-compat>=2.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (2.2.1)
Requirement already satisfied: click<9,>=8.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (8.0.3)
Requirement already satisfied: click-help-colors>=0.9 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (0.9.1)
Requirement already satisfied: cookiecutter>=1.7.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (2.1.1)
Requirement already satisfied: enrich>=1.2.7 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (1.2.7)
Requirement already satisfied: jsonschema>=4.9.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (4.16.0)
Requirement already satisfied: Jinja2>=2.11.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (3.1.2)
Requirement already satisfied: packaging in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.7.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (1.0.0)
Requirement already satisfied: PyYAML>=5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (6.0)
Requirement already satisfied: rich>=9.5.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from molecule==4.0.3->-r requirements.txt (line 6)) (12.6.0)
Requirement already satisfied: subprocess-tee>=0.3.5 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from ansible-compat>=2.2.0->molecule==4.0.3->-r requirements.txt (line 6)) (0.3.5)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cffi>=1.12->cryptography==38.0.1->-r requirements.txt (line 1)) (2.21)
Requirement already satisfied: binaryornot>=0.4.4 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (0.4.4)
Requirement already satisfied: jinja2-time>=0.2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: python-slugify>=4.0.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (6.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from Jinja2>=2.11.3->molecule==4.0.3->-r requirements.txt (line 6)) (2.1.1)
Requirement already satisfied: attrs>=17.4.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jsonschema>=4.9.1->molecule==4.0.3->-r requirements.txt (line 6)) (22.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jsonschema>=4.9.1->molecule==4.0.3->-r requirements.txt (line 6)) (0.18.1)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich>=9.5.1->molecule==4.0.3->-r requirements.txt (line 6)) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from rich>=9.5.1->molecule==4.0.3->-r requirements.txt (line 6)) (2.13.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from packaging->molecule==4.0.3->-r requirements.txt (line 6)) (3.0.9)
Requirement already satisfied: chardet>=3.0.2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from binaryornot>=0.4.4->cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (5.0.0)
Requirement already satisfied: arrow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2-time>=0.2.0->cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (1.2.3)
Requirement already satisfied: text-unidecode>=1.3 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from python-slugify>=4.0.0->cookiecutter>=1.7.3->molecule==4.0.3->-r requirements.txt (line 6)) (1.3)

**Comment by c-herz** [comment]
Apologies for the late reply--I don't think this is an issue with this project, per say, but more likely an issue with your Python installation. If you still haven't gotten it to work, maybe try setting up a virtual Python environment? If reinstalling Python and trying this still doesn't work, maybe try with an earlier version of Python such as 3.9.

**Comment by realtkco** [comment]
I was experiencing this issue in my WSL (Ubuntu 20.04) environment. I dismissed it thinking it was due to me using python3.6 instead of python directly. I went directly to my windows environment and it worked perfectly.
