### ISSUE TITLE
Enable both 2.4GHz and 5GHz WiFi networks

### ISSUE THREAD

**Issue by Zero3K** [c-herz/TMOHS1-Root-Utility#7]
Is it possible to do that after using this root utility?

**Comment by Rudi9719** [comment]
I don't see a way to do this, however [ 2.4GHz looks like it's being phased out starting with Android 12](https://www.androidpolice.com/2021/04/22/android-12-really-wants-you-to-use-5ghz-wi-fi-in-hotspot-mode/), so it's possible that these devices may eventually phase out 2.4GHz. 

As for supporting both networks at the same time, iirc this device doesn't have enough antennae to run two hotspots at once. Most routers that support this function have multiple antennae for each (2.4/5) band they run. Under the hood, this device isn't a real router/access point- it's actually just an Android 'phone' running a custom webUI that turns tethering on at boot.

**Comment by c-herz** [comment]
I'm not sure the device is capable of doing this, though if I am not wrong there may be another antenna port on the board. If this is the case, it's possible it does have the capability to use two antennas, just that one is not operational. I haven't looked much into this, though.
