### ISSUE TITLE
Change IMEI

### ISSUE THREAD

**Issue by IamRico00** [c-herz/TMOHS1-Root-Utility#8]
Awesome utility
Works great on TMOHS1
All data is routed through "non tethering" data
Is it possible to change the IMEI? I did the same on prior T9s which allowed tmobile to recognize them as phones which completed the effect to go with "non tethering" data (by changing the TLS data).

Mood lighting doesnt keep after reboot for some reason

thanks
Rico

**Comment by parambil** [comment]
Option to update IMEI will be really helpful.

**Comment by c-herz** [comment]
Apologies, but if I'm not mistaken the legality of changing the IMEI of a device to "spoof" a different one is questionable at best, so I'm not sure I would feel comfortable implementing that (nor do I even know how, as this requires privileged communication with the modem subprocessor to my knowledge, and the proprietary protocols involved would require some serious reverse engineering). If you can figure out how to do it though, you're welcome to try. And in regard to the mood lighting, to get it to persist you would need to edit the init scripts.

**Comment by parambil** [comment]
That's good to know.
